export const siteConfig = {
  name: "Soumya Mukherjee",
  shortName: "soumya",
  title: "soumya",
  description:
    "Frontend engineer crafting polished interfaces with React, Next.js and TypeScript. Focused on clean code, smooth animations and interactions that feel effortless.",
  url: "https://deathstalker.dev",
  ogImage: "https://deathstalker.dev/og.png",
  author: {
    name: "Soumya Mukherjee",
    email: "soumyamukherjee.work@gmail.com",
    twitter: "@0xdeathstalker",
    github: "0xdeathstalker",
    linkedin: "soumya-mukherjee-88a551248",
  },
  links: {
    twitter: "https://x.com/0xdeathstalker",
    github: "https://github.com/0xdeathstalker",
    linkedin: "https://www.linkedin.com/in/soumya-mukherjee-88a551248/",
  },
  keywords: [
    "Soumya Mukherjee",
    "Design Engineer",
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Web Developer",
    "Portfolio",
    "Software Engineer",
    "UI Developer",
    "JavaScript",
    "UI/UX Developer",
    "Creative Developer",
    "Interface Design",
    "Motion Design",
    "Framer Motion",
  ],
} as const;
